### ISSUE TITLE
Smashline 2 Updates

### ISSUE THREAD

**Issue by LilyLavender** [LilyLavender/smashline-tutorial#9]
# Todo: Update the repo for Smashline 2
Gonna include Smashline 2 stuff alongside 1. I want the repo to be an easy place to copy-paste code from, so for now, both Smashline 1 and 2 will be included.

## Episode List
Any episodes not listed don't need to be updated
- [ ] 2. Basic File Structure
- [ ] 3. Changing Hitbox Data
- [ ] 5. Effects & Backgrounds
- [ ] 6. Porting Moves
- [ ] 8. Damage & Healing
- [ ] 9. Getting Player Inputs
- [ ] 10. Transitioning Into Moves
- [ ] 11. Fighter Frames
- [ ] 12. All About Frames
- [ ] 13. Teleportation & Movement
- [ ] 14. Crits & Randomness
- [ ] 15. Super Armor & Invincibility
- [ ] 16. Reflectors
- [ ] 17. Multipliers
- [ ] 18. Velocity
- [ ] 19. Direction
- [ ] 20. Changing Size
- [ ] 21. Slowing Time
- [ ] 22. Spawning Items & Articles
- [ ] 23. Visibility
- [ ] 24. Slotting Part 1
- [ ] 27. Hit Detection
- [ ] 30. Status Scripts Part 2
- [ ] 31. My Resources Part 2
- [ ] 32. Sounds
- [ ] 33. Expressions
- [ ] 34. Items
- [ ] 35. Getting Parameters
- [ ] 36. Status Kinds
- [ ] 37. Debugging with println
- [ ] 38. Adding Moves
- [ ] 39. Adding A Sword
- [ ] 40. Adding Sword Trails (only example 1)
- [ ] 41. Slotting Part 2
- [ ] 42. Status Scripts Part 3
- [ ] 43. Status Scripts Part 4
- [ ] 44. Projectiles
- [ ] 45. Command Inputs
